set(TOOLCHAIN_PATH "/home/andi/x-tools/arm-unknown-linux-gnueabi/bin/")

set(CMAKE_C_COMPILER ${TOOLCHAIN_PATH}arm-unknown-linux-gnueabi-gcc${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PATH}arm-unknown-linux-gnueabi-g++${CMAKE_EXECUTABLE_SUFFIX})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
